#!/usr/bin/env python3
"""Generate the complete package list and content-versioned offline inventory.

The service worker imports cache-manifest.js. Changing any shipped file changes
that imported script, which triggers an offline cache update even if the worker
source itself has not changed. There is no application server or JS build tool.
"""

import argparse
import hashlib
import json
import tempfile
from pathlib import Path

SHELL = (
    "index.html",
    "bootstrap.js",
    "kana.html",
    "kana.css",
    "kana.js",
    "kana-worker.js",
    "manifest.webmanifest",
    "service-worker.js",
    "icons/icon-192.png",
    "icons/icon-512.png",
    "icons/icon-maskable-512.png",
    "icons/apple-touch-icon.png",
)
GENERATED = {"asset-manifest.json", "cache-manifest.js"}


def generate(web):
    package = web / "pkg"
    files = sorted(
        p
        for p in package.rglob("*")
        if p.is_file() and p.name not in GENERATED | {".gitignore"}
    )
    if not files:
        raise ValueError(
            "build the Wasm packages before generating the offline inventory"
        )
    paths = sorted([web / name for name in SHELL] + files)
    digest = hashlib.sha256()
    for path in paths:
        name = path.relative_to(web).as_posix().encode()
        content = path.read_bytes()
        digest.update(len(name).to_bytes(8, "big"))
        digest.update(name)
        digest.update(len(content).to_bytes(8, "big"))
        digest.update(content)
    package_assets = sorted(
        ["./" + p.relative_to(web).as_posix() for p in files]
        + ["./pkg/cache-manifest.js"]
    )
    inventory = {
        "version": digest.hexdigest(),
        "assets": sorted(
            {
                "./",
                "./pkg/asset-manifest.json",
                *package_assets,
                *("./" + name for name in SHELL),
            }
        ),
    }
    outputs = {
        "asset-manifest.json": json.dumps(package_assets, indent=2) + "\n",
        "cache-manifest.js": "// Generated by tools/write-web-manifest.py; do not edit.\nself.IDIOSEPIUS_OFFLINE = "
        + json.dumps(inventory, indent=2)
        + ";\n",
    }
    for filename, content in outputs.items():
        with tempfile.NamedTemporaryFile(
            mode="w", dir=package, delete=False, encoding="utf-8"
        ) as pending:
            pending.write(content)
            temporary = Path(pending.name)
        temporary.replace(package / filename)
    return inventory


def self_test():
    with tempfile.TemporaryDirectory() as directory:
        web = Path(directory)
        for name in SHELL:
            p = web / name
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(name)
        (web / "pkg/snippets/hash").mkdir(parents=True)
        (web / "pkg/snippets/hash/extra.js").write_text("export const x = 1")
        (web / "pkg/main.wasm").write_bytes(b"wasm-one")
        first = generate(web)
        assert first == generate(web), "generated files changed their own digest"
        assert "./pkg/snippets/hash/extra.js" in first["assets"]
        (web / "pkg/main.wasm").write_bytes(b"wasm-two")
        second = generate(web)
        assert first["version"] != second["version"], "model/build update was invisible"
        (web / "kana.js").write_text("new shell")
        assert generate(web)["version"] != second["version"], (
            "shell update was invisible"
        )
        package = json.loads((web / "pkg/asset-manifest.json").read_text())
        assert package == sorted(package) and "./pkg/cache-manifest.js" in package
    print("Offline inventory generation tests passed")


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "web",
        nargs="?",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "web",
    )
    p.add_argument("--self-test", action="store_true")
    a = p.parse_args()
    if a.self_test:
        self_test()
    else:
        inventory = generate(a.web)
        print(
            f"Offline build {inventory['version'][:16]}: {len(inventory['assets'])} assets"
        )


if __name__ == "__main__":
    main()
